eshop.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eshop.Application.Interface;
using eshop.Core;
using Microsoft.AspNet.Identity;

namespace eshop.Web.Controllers
{
    public class OrdersController : Controller
    {

        public IOrdersBL OrdersBL { get; set; }//declaramos la variable 
        public ILineOfOrdersBL LineOfOrdersBL { get; set; }


        public OrdersController(IOrdersBL ordersBL, ILineOfOrdersBL lineOfOrdersBL) { //inicializamos la variable 
            OrdersBL = ordersBL;
            LineOfOrdersBL = lineOfOrdersBL;

        }

        [HttpGet]
        public ActionResult GetByUser()
        {
            var userId = User.Identity.GetUserId();
            var result = OrdersBL.GetOrdersByUser(userId);
            return PartialView("_PartialPageOrdersByUser", result);
        }

        // GET: Orders
        public ActionResult Index()
        {
        
            return View();
        }

        public ActionResult EndOrder()
        {
            if (User.Identity.GetUserId() == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Order orderSesion = (Order)Session["order"];
            return View(orderSesion);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateOrder(Order order, int productId)
        {
            var user = User.Identity.GetUserId();
            if (user == null)
            {
                var url = new UrlHelper(Request.RequestContext).Action("Login", "Account");
                return Json(new { redirecturl = url });
            }

            order.UserId = user;
            order = OrdersBL.CreateOrder(order);

            LineOfOrder lineOfOrder = new LineOfOrder()
            {
                OrderId = order.Id,
                ProductId = productId
            };
            lineOfOrder=LineOfOrdersBL.CreateLine(lineOfOrder);
            order.LineOfOrder.Add(lineOfOrder);
            Session["order"] = order;
            return Json(new { count= order.LineOfOrder.Count});
        }

        [HttpPut]
        public ActionResult UpdateOrder(int productId)
        {
            Order order = (Order)Session["order"];
            var user = User.Identity.GetUserId();
            if (user == null)
            {
                var url = new UrlHelper(Request.RequestContext).Action("Login", "Account");
                return Json(new { redirecturl = url });
            }
            LineOfOrder lineOfOrder=null;
            for (int i=0; i < order.LineOfOrder.Count; i++)
            {
                if (order.LineOfOrder.ToList()[i].ProductId==productId)
                {
                    lineOfOrder = order.LineOfOrder.ToList()[i];
                    lineOfOrder.Quantity++;
                    order.LineOfOrder.ToList()[i] = LineOfOrdersBL.UpdateLine(lineOfOrder);
                    break;
                }
            }

            if (lineOfOrder==null)
            {
                lineOfOrder = new LineOfOrder()
                {
                    OrderId = order.Id,
                    ProductId = productId
                };
                lineOfOrder=LineOfOrdersBL.CreateLine(lineOfOrder);
                order.LineOfOrder.Add(lineOfOrder);
            }
            Session["order"] = order;
            return Json(new { count = order.LineOfOrder.Count });

        }

        [HttpPut]
        public ActionResult UpdateLine(int id, int quantity)
        {
            Order order = (Order)Session["order"];
            LineOfOrder lineOfOrder = order.LineOfOrder.FirstOrDefault(x => x.Id == id);
            lineOfOrder.Quantity = quantity;
            lineOfOrder.DateLOrderModification = DateTime.Now;
            Session["order"] = order;
            return Json(new { });
        }

        [HttpPut]
        public ActionResult FinishOrder()
        {
            Order order = (Order)Session["order"];
            OrdersBL.UpdateOrder(order);

            Session.Remove("order");
            var url = new UrlHelper(Request.RequestContext).Action("Index", "Home");
            return Json(new { redirecturl = url });
        }

        [HttpDelete]
        public ActionResult DeleteLine(int id)
        {
            Order order = (Order)Session["order"];
            LineOfOrdersBL.DeleteLine(id);
            LineOfOrder lineOfOrder = order.LineOfOrder.SingleOrDefault(x => x.Id == id);
            order.LineOfOrder.Remove(lineOfOrder);
            Session["order"] = order;
            return Json(new { count = order.LineOfOrder.Count });
        }

        // POST: Orders/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Orders/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Orders/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

eshop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("styles", required: false)
    <script type="text/javascript" src="~/Scripts/card.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
            @Html.ActionLink("E-Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (User.IsInRole("Admin"))
                    {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            Administration
                        </a>
                        <div class="dropdown-menu">
                            @Html.ActionLink("AdminProducts", "AdminProducts", "AdminProducts", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("AdminUsers", "AdminUsers", "AdminProducts", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("AdminOrders", "AdminOrders", "AdminProducts", new { area = "" }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    }
                </ul>
                <ul class="nav navbar-nav ml-auto">
                    @Html.Partial("_LoginPartial")
                    <li class="nav-item" style="position:relative;">
                        <a class="nav-link" style="height:100%; cursor:pointer;" id="cart">
                            <img style="width:20px;" src="~/Content/Images/cart.svg" />
                            @if ((eshop.Core.Order)Session["order"] != null)
                            {
                                var order = (eshop.Core.Order)Session["order"];
                                <span class="badge badge-count">@order.LineOfOrder.Count</span>
                            }
                            else
                            {
                                <span class="badge badge-count">0</span>
                            }

                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="shopping-cart">

        </div> <!--end shopping-cart -->
        <div class="content">
            @RenderBody()
        </div>
        <div class="footer-content">
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year Eshop Comapny</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/Ajax")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        (function () {

            $("#cart").on("click", function () {
                var url = 'Home/GetCart';
                Common.Ajax('GET', url, null, 'html', showCart);
            });

        })();
        function showCart(result) {
            $('.shopping-cart').html(result);
            $(".shopping-cart").fadeToggle("fast");
        }
    </script>
</body>
</html>

eshop.Web/Views/Shared/_PartialCartDesc.cshtml
@model eshop.Core.Order

<div class="shopping-cart-header">
    <img style="width:20px;" src="~/Content/Images/cart.svg" />
    <div class="shopping-cart-total">
        <span class="lighter-text">Total:</span>
        @{double totalValue = 0; }
        @if (Model != null)
        {
            foreach (var lineOfOrder in Model.LineOfOrder)
            {
                { totalValue += (lineOfOrder.Price * lineOfOrder.Quantity); }
            }
        }
        <span class="main-color-text">@totalValue € </span>
    </div>
</div> <!--end shopping-cart-header -->
@if (Model != null && Model.LineOfOrder.Count!=0)
{
    foreach (var lineOfOrder in Model.LineOfOrder)
    {
        <ul class="shopping-cart-items">
            <li class="clearfix">
                @if (lineOfOrder.Product.Image.Count == 0)
                {
                    <img src="http://placehold.it/60x83" alt="Placholder Image " class="product-frame">
                }
                else
                {
                    <img src="~/Content/Images/@lineOfOrder.Product.Image.ToList()[0].Name" alt="Placholder Image " style="width:60px;height:83px;" class="product-frame">
                }

                <span class="item-name">@lineOfOrder.Product.Name</span>
                <span class="item-price">@(lineOfOrder.Quantity * lineOfOrder.Price) €</span>
                <span class="item-quantity">Quantity: @lineOfOrder.Quantity</span>
            </li>
        </ul>
    }
    @Html.ActionLink("Checkout", "EndOrder", "Orders", new { area = "" }, new { @class = "button" })
}
else
{
    <span>Empty cart</span>
}

eshop.Web/Views/Shared/_PartialPageAdminOrders.cshtml
@model  List<eshop.Core.Order>

@foreach (var order in Model)
{
    <tr>
        <td class="id">@order.Id</td>
        <td class="email">@order.AspNetUsers.Email</td>
        <td class="lineordercount">@order.LineOfOrder.Count</td>
        <td class="state">@(Enum.GetName(typeof(eshop.DAL.eshopENUM.TypeState), order.StateId))</td>
        <td class="orderCreation">@order.DateOrderCreation</td>
        <td> <a href="#" class="btn btn-primary act">Editar</a></td>

    </tr>
}

eshop.Web/Views/Shared/_PartialPageAdminProducts.cshtml
@model  List<eshop.Core.Product>

@foreach (var prod in Model)
{
    <tr>
        <td class="id">@prod.Id</td>
        <td class="name">@prod.Name</td>
        <td class="description">@prod.Description</td>
        <td class="price">@prod.PriceProduct</td>
        <td class="stock">@prod.Stock</td>
        <td> <a href="#" class="btn btn-primary act">Editar</a></td>

    </tr>
}
<script>
    $('a.act').on('click', function () {
    var myModal = $('#exampleModal');
    console.log('hola')
    // now get the values from the table
    var id = $(this).closest('tr').find('td.id').html();
    var name = $(this).closest('tr').find('td.name').html();
    var desc = $(this).closest('tr').find('td.description').html();
    var price = $(this).closest('tr').find('td.price').html();
    var stock = $(this).closest('tr').find('td.stock').html();


    // and set them in the modal:
    $('#Id', myModal).val(id);
    $('#Name', myModal).val(name);
    $('#Description', myModal).val(desc);
    $('#PriceProduct', myModal).val(price);
    $('#Stock', myModal).val(stock);


    // and finally show the modal
    myModal.modal('show');

    return false;
});
</script>

eshop.Web/Views/Shared/_PartialPageAdminUsers.cshtml
@model List<eshop.Core.AspNetUsers>
@foreach (var user in Model)
{
    <tr>
        <td class="id">@user.Id</td>
        <td class="userName">@user.UserName</td>
        <td class="email">@user.Email</td>
        <td class="role">@user.AspNetRoles.First().Name</td>
        <td> <a href="#" class="btn btn-primary act" onclick="changeRole(@user.Id)">Change to Admin/Client</a></td>
    </tr>
}

eshop.Web/Views/Shared/_PartialPageOrdersByUser.cshtml
@model  List<eshop.Core.Order>

@foreach (var order in Model)
{
    <tr>
        <td class="id">@order.Id</td>
        <td class="lineordercount">@order.LineOfOrder.Count</td>
        <td class="state">@(Enum.GetName(typeof(eshop.DAL.eshopENUM.TypeState), order.StateId))</td>
        <td class="orderCreation">@order.DateOrderCreation</td>
        <td class="orderModify">@order.DateOrderModification</td>
    </tr>
}

eshop.Web/Views/Shared/_ProductsPartial.cshtml
@model  List<eshop.Core.Product>

@if (Model != null)
{
    <div class="card-deck">

        @{ var count = 0; }
        @foreach (var prod in Model) //guardamos la varaible entera mejor que for
        {
            <div class="card">
                <div id="carouselExampleControls@(prod.Id)" class="carousel slide" data-ride="carousel">
                    @if (prod.Image.Count > 0)
                    {
                    <div class="carousel-inner">
                        @{ var firstImg = 0; }
                        @foreach (var img in prod.Image)
                        {
                            if (firstImg == 0)
                            {
                                <div class="carousel-item active">

                                    <img class="d-block" style="width:270px;height:332px; margin-left:28%;" src="~/Content/Images/@img.Name" alt="">
                                </div>
                            }
                            else
                            {
                                <div class="carousel-item">

                                    <img class="d-block" style="width:270px;height:332px; margin-left:28%;" src="~/Content/Images/@img.Name" alt="">
                                </div>
                            }
                            { firstImg++;}

                        }
                    </div>
                    
                
                        <a class="carousel-control-prev" href="#carouselExampleControls@(prod.Id)" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls@(prod.Id)" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    }
                    else
                    {
                        <div class="carousel-inner" style="display:flex; justify-content:center;">
                            <img class="d-block " src="http://placehold.it/270x332" alt="Placholder Image ">
                        </div>
                    }

                </div>


                <div class="card-body">
                    <div style="display:flex; justify-content:center;">
                        <h4 class="card-title">@prod.Name</h4>
                    </div>
                    <div style="display:flex;">
                        <strong style="width:25%">Description: </strong>
                        <p style="width:75%;" class="card-text">@prod.Description</p>
                    </div>
                    <div style="display:flex;">
                        <strong style="width:25%;">Price: </strong>
                        <span style="width:75%;">@prod.PriceProduct €</span>
                    </div>

                </div>
                <div class="card-footer">

                    @if (prod.Stock == 0)
                    {
                        <span style="color:red; font-weight:bold;">Product without stock.</span>
                    }
                    else
                    {
                        if (prod.Stock < 25)
                        {
                            <small style="color:orange; font-weight:bold;">Last units.</small>
                        }
                        <button class="btn btn-info" style="float:right;" onclick="addToCart(@prod.Id)">Add Product</button>
                    }
                </div>
                @{ count++;}

            </div>
            if (count % 2 == 0)
            {
            @:</div>


            @:<div class="card-deck">


            }
        }
    </div>

}